### ISSUE TITLE
Add option to contextualize tags

### ISSUE THREAD

**Issue by JeremyTheocharis** [united-manufacturing-hub/benthos-umh#1]
Currently, it browses the selected nodeIDs and just pushes it into the Unified Namespace.

We could add a separate function linke ExactNodeIDs:

```yaml
input:
  opcua:
    endpoint: 'opc.tcp://localhost:46010'
    exactNodeIDs:
      - tag: 'ns=2;s=IoTSensors'
        enterprise: 'factoryinsight'
        ....
        workCell: 'simulator123'
        renameTo: 'Temperature'
 ```
