### ISSUE TITLE
S7-Addressing adjustment for PA/PE/MK maybe C and T

### ISSUE THREAD

**Issue by led0nk** [united-manufacturing-hub/benthos-umh#152]
```yaml
---
input:
  s7comm:
    tcpDevice: 10.13.37.198
    rack: 0
    slot: 1
    addresses:
      - PA0.X0.0
      - PA0.X0.1
      - PA0.X0.2
      - PA0.X0.3

      # basically the same
      - PA360.X0.0
      - PA360.X0.1
      - PA360.X0.2
      - PA360.X0.3
```

When trying to connect via `s7comm` it appears that if you try to read data from 

- process inputs
- process outputs
- merkers
- counters / timers (not sure on that) 

the addressing is somehow weird, since you basically don't have any need to provide the DBNumber. 

Addressing for data blocks works like this:

`DB2.X0.3` -> data block 2 bit-no. 4 of byte 0 (or offset 0)

But for outputs/inputs/merkers it should look like this:

`PA.X0.3`-> Just because they're not kind of data instances. The PLC just creates an image of the inputs -> `PE` -> takes that into the plc-cycle and writes outputs into -> `PA` 

Merkers are basically addressed the same.

Also add some examples in Readme for this cases, since this is not quite obvious.
