### ISSUE TITLE
[Bug] Implement error handling for bad data

### ISSUE THREAD

**Issue by devantler** [united-manufacturing-hub/benthos-umh#16]
During testing of `benthos-umh` I found that it crashes if bad data is returned. I think it would be nice if error handling was implemented, such that bad data is caught, but that it does not crash the service completely.

I tested it with this docker-compose stack:

```yaml
services:
  benthos-umh:
    image: devantler/benthos-umh-fixed:latest # uses the image from #12 
    volumes:
      - ./docker/benthos-umh-data/benthos.yaml:/benthos.yaml

  opc-plc:
    image: mcr.microsoft.com/iotedge/opc-plc:2.9.11
    ports:
      - 8080:8080 # This port is only used to access the OPC Publisher configuration file on http://localhost:8080/pn.json. (remove if --showpnjsonph argument is deleted).
    command:
      - --autoaccept # all certs are trusted when a connection is established.
      - --showpnjsonph # show OPC Publisher configuration file using plchostname as EndpointUrl.
      - --certdnsnames=opc-plc # DNS names to add to the certificate.
```

And this `benthos.yaml` configuration:

```yaml
input:
  opcua:
    endpoint: opc.tcp://opc-plc:50000
    nodeIDs:
      - ns=3;s=BadFastUInt1
    securityMode: SignAndEncrypt
    securityPolicy: Basic256Sha256

pipeline:
  processors:
    - mapping: root = if errored() { deleted() }

output:
  stdout:
    codec: lines
```

**Comment by JeremyTheocharis** [comment]
What do you mean with BadData? We typically program our microservices that they fail very visible (by restarting) so that it becomes very obvious that something bad happened.

**Comment by devantler** [comment]
We use microsofts OPC-PLC server for testing purposes [mcr.microsoft.com/iotedge/opc-plc:2.9.11](https://learn.microsoft.com/en-us/samples/azure-samples/iot-edge-opc-plc/azure-iot-sample-opc-ua-server/).

This server supports fabricating a lot of different data. One of these data formats is a bad UInt8 value. I am not sure what exactly is "bad" about it as this is not well documented, and I was not able to infer it from their [code](https://github.com/Azure-Samples/iot-edge-opc-plc/blob/98d6c53b221b799ec9dd9426d81e99bb08cfe4a5/src/PluginNodes/SlowFastCommon.cs#L115).

My expectation, however, is that Benthos should be able to handle cases where the data it receives is "unknown", causes exceptions, or is in other ways unsupported. In regular benthos flows, I would, for example, be able to handle this with the following pipeline:

```yaml
pipeline:
  processors:
    - mapping: root = if errored() { deleted() }
```

In this case, however, the data causes the whole `benthos-um` service to crash, which I think should not be the case. The error is as follows:

```txt
level=info msg="Connected to opc.tcp://opc-plc:50000" @service=benthos label="" path=root.input
level=info msg="Please note that browsing large node trees can take a long time (around 5 nodes per second)" @service=benthos label="" path=root.input
level=info msg="Detected nodes: [{\"NodeID\":\"ns=3;s=BadFastUInt1\",\"NodeClass\":2,\"BrowseName\":\"BadFastUInt1\",\"Description\":\"Constantly increasing value(s)\",\"AccessLevel\":0,\"Path\":\"BadFastUInt1\",\"DataType\":\"uint32\",\"Writable\":false,\"Unit\":\"\",\"Scale\":\"\",\"Min\":\"\",\"Max\":\"\"}]" @service=benthos label="" path=root.input
level=error msg="Status not OK: Whatever was updating this value has stopped doing so. StatusUncertainLastUsableValue (0x40900000)" @service=benthos label="" path=root.input
level=error msg="Status not OK: Data is missing due to collection started/stopped/lost. StatusBadDataLost (0x809D0000)" @service=benthos label="" path=root.input
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x220da68]

goroutine 18 [running]:
github.com/gopcua/opcua/ua.(*Variant).Value(...)
        /go/pkg/mod/github.com/gopcua/opcua@v0.5.2/ua/variant.go:114
github.com/united-manufacturing-hub/benthos-umh/v2/plugin.(*OPCUAInput).ReadBatchPull(0x4000df6f20, {0x34b0b58, 0x4000cd0190})
        /go/src/github.com/united-manufacturing-hub/benthos-umh/plugin/opcua.go:621 +0x728
github.com/united-manufacturing-hub/benthos-umh/v2/plugin.(*OPCUAInput).ReadBatch(0x34b0b58?, {0x34b0b58?, 0x4000cd0190?})
        /go/src/github.com/united-manufacturing-hub/benthos-umh/plugin/opcua.go:689 +0x3c
github.com/benthosdev/benthos/v4/public/service.(*autoRetryInputBatched).ReadBatch(0x4001528940, {0x34b0b58?, 0x40012b8190?})
        /go/pkg/mod/github.com/benthosdev/benthos/v4@v4.7.0/public/service/input_auto_retry_batched.go:102 +0x458
github.com/benthosdev/benthos/v4/public/service.(*airGapBatchReader).ReadBatch(0x400175fee8?, {0x34b0b58?, 0x40012b8190?})
        /go/pkg/mod/github.com/benthosdev/benthos/v4@v4.7.0/public/service/input.go:158 +0x30
github.com/benthosdev/benthos/v4/internal/component/input.(*AsyncReader).loop(0x400042eea0)
        /go/pkg/mod/github.com/benthosdev/benthos/v4@v4.7.0/internal/component/input/async_reader.go:123 +0x36c
created by github.com/benthosdev/benthos/v4/internal/component/input.NewAsyncReader in goroutine 1
        /go/pkg/mod/github.com/benthosdev/benthos/v4@v4.7.0/internal/component/input/async_reader.go:57 +0x234
```
